language: csharp
solution: ./Celloc.DataTable.Aggregations.sln
install:
  - nuget restore ./Celloc.DataTable.Aggregations.sln
  - nuget install NUnit.ConsoleRunner -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./Celloc.DataTable.Aggregations.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Celloc.DataTable.Aggregations.Tests/bin/Release/Celloc.DataTable.Aggregations.Tests.dll
